### PR TITLE
support Scala 2.12

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by eed3si9n** [comment]
I think we want 2.10 while sbt is still on 2.10 so we can do things like sbt-site integration.

**Comment by xuwei-k** [comment]
Hmmm, I just released knockoff 0.8.5 with Scala 2.10 support. but can't use 0.8.5 due to https://github.com/foundweekends/knockoff/commit/2c256bb0212d296cc310820ac8f18f4ef34bacaa

```
pamflet/knockoff/src/main/scala/fenced.scala:75: illegal inheritance from sealed class Chunk
[error] extends Chunk {
[error]         ^
[error] one error found
[error] (knockoff/compile:compileIncremental) Compilation failed
```

Should I revert https://github.com/foundweekends/knockoff/commit/2c256bb0212d296cc310820ac8f18f4ef34bacaa ?

**Comment by eed3si9n** [comment]
> Should I revert foundweekends/knockoff@2c256bb ?

I guess so.

**Comment by xuwei-k** [comment]
I'll fix and release knockoff 0.8.6.

**Pull request merged**
